"""Fixed 2 annotatorssssssssssxs

Revision ID: 0938483ff257
Revises: da053ebc8736
Create Date: 2025-05-24 00:37:17.540975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0938483ff257'
down_revision = 'da053ebc8736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.drop_column('model_annotation_done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_annotation_done', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
