"""Add is_verified field to User model and vt

Revision ID: 113cddec6c1b
Revises: cec6ebaeb3d4
Create Date: 2025-02-05 21:52:49.116236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113cddec6c1b'
down_revision = 'cec6ebaeb3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
