"""Added lock_time and in_progress_by columns to Review model

Revision ID: 2a5183a6df6d
Revises: dd1e557d99b5
Create Date: 2024-11-06 02:46:32.101130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5183a6df6d'
down_revision = 'dd1e557d99b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('in_progress_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_review_in_progress_by', 'user', ['in_progress_by'], ['id'])

    # ### end Alembic commands ###


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('in_progress_by')
        batch_op.drop_column('lock_time')

    # ### end Alembic commands ###
