"""Add uploaded_by column to CSVFile

Revision ID: 337aeec538ee
Revises: 
Create Date: 2024-11-12 02:59:46.760218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337aeec538ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('completed_courses', sa.String(length=150), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('completed_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('annotator_1_id', sa.Integer(), nullable=True),
    sa.Column('annotation_1', sa.Text(), nullable=True),
    sa.Column('annotator_2_id', sa.Integer(), nullable=True),
    sa.Column('annotation_2', sa.Text(), nullable=True),
    sa.Column('annotator_3_id', sa.Integer(), nullable=True),
    sa.Column('annotation_3', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['annotator_2_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['annotator_3_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=150), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('annotation_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('csv_file_id', sa.Integer(), nullable=False),
    sa.Column('lock_time', sa.DateTime(), nullable=True),
    sa.Column('in_progress_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['csv_file_id'], ['csv_file.id'], ),
    sa.ForeignKeyConstraint(['in_progress_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('annotation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation')
    op.drop_table('review')
    op.drop_table('csv_file')
    op.drop_table('completed_review')
    op.drop_table('user')
    # ### end Alembic commands ###
