"""Fixed 2 annotatorss

Revision ID: 53a10ade7b13
Revises: 728f11ae43a0
Create Date: 2025-05-06 00:46:21.433413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a10ade7b13'
down_revision = '728f11ae43a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('csv_file_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('completed_courses', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('experience_years')
        batch_op.drop_column('completed_courses')
        batch_op.drop_column('department')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('csv_file_invite', schema=None) as batch_op:
        batch_op.drop_column('accepted_at')

    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
