"""empty message

Revision ID: 6719a81be94e
Revises: 51422b574947
Create Date: 2024-12-21 23:11:01.701922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6719a81be94e'
down_revision = '51422b574947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csv_file_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'csv_file', ['csv_file_id'], ['id'])
        batch_op.drop_column('annotation_2')
        batch_op.drop_column('annotation_3')
        batch_op.drop_column('annotation_1')

    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_csv_file_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['uploaded_by'], ['id'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_review_csv_file_id'), ['csv_file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_csv_file_id'))
        batch_op.drop_column('completed')

    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_csv_file_uploaded_by'))
        batch_op.drop_column('is_active')
        batch_op.drop_column('uploaded_by')

    with op.batch_alter_table('completed_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotation_1', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('annotation_3', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('annotation_2', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('csv_file_id')

    # ### end Alembic commands ###
