"""Fixed 2 annotators

Revision ID: 728f11ae43a0
Revises: bf75ef8cc677
Create Date: 2025-05-06 00:42:35.390374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728f11ae43a0'
down_revision = 'bf75ef8cc677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_review', schema=None) as batch_op:
        batch_op.drop_constraint('fk_completed_review_annotator_3_id', type_='foreignkey')
        batch_op.drop_column('annotator_3_id')
        batch_op.drop_column('annotation_3')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('completed_courses')
        batch_op.drop_column('department')
        batch_op.drop_column('experience_years')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_years', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('completed_courses', sa.VARCHAR(length=150), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('completed_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotation_3', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('annotator_3_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_completed_review_annotator_3_id', 'user', ['annotator_3_id'], ['id'])

    # ### end Alembic commands ###
