"""Add is_verified field to User model234

Revision ID: 76638f27a4ad
Revises: 8d6252dddb6f
Create Date: 2025-02-12 00:03:59.365166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76638f27a4ad'
down_revision = '8d6252dddb6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_verified', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
