"""Add is_verified field to User model23

Revision ID: 8d6252dddb6f
Revises: b8a7cb884c4c
Create Date: 2025-02-10 22:03:18.641319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6252dddb6f'
down_revision = 'b8a7cb884c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_verified')

    # ### end Alembic commands ###
