"""Validate schema after manual update

Revision ID: ae1681318959
Revises: 6719a81be94e
Create Date: 2024-12-21 23:36:10.956458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1681318959'
down_revision = '6719a81be94e'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('completed_review', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_completed_review_csv_file_id',
            'csv_file',
            ['csv_file_id'],
            ['id']
        )
        batch_op.create_foreign_key(
            'fk_completed_review_annotator_1_id',
            'user',
            ['annotator_1_id'],
            ['id']
        )
        batch_op.create_foreign_key(
            'fk_completed_review_annotator_2_id',
            'user',
            ['annotator_2_id'],
            ['id']
        )
        batch_op.create_foreign_key(
            'fk_completed_review_annotator_3_id',
            'user',
            ['annotator_3_id'],
            ['id']
        )

    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), default=True))
        batch_op.create_foreign_key(
            'fk_csv_file_uploaded_by',
            'user',
            ['uploaded_by'],
            ['id']
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('completed')

    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('completed_review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
