"""Add is_verified field to User model1

Revision ID: b8a7cb884c4c
Revises: 113cddec6c1b
Create Date: 2025-02-06 21:56:48.834691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a7cb884c4c'
down_revision = '113cddec6c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
