"""Add is_verified field to User model2345

Revision ID: bf75ef8cc677
Revises: 76638f27a4ad
Create Date: 2025-02-12 21:10:33.330211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf75ef8cc677'
down_revision = '76638f27a4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_file_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csv_file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['csv_file_id'], ['csv_file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csv_file_invite')
    # ### end Alembic commands ###
