"""Fixed 2 annotatorssssssss

Revision ID: da053ebc8736
Revises: e3f1c4492c6a
Create Date: 2025-05-18 13:54:49.234552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da053ebc8736'
down_revision = 'e3f1c4492c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_annotation_done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.drop_column('model_annotation_done')

    # ### end Alembic commands ###
