"""Updated models

Revision ID: dd1e557d99b5
Revises: 435441f737d8
Create Date: 2024-11-06 02:27:10.250369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1e557d99b5'
down_revision = '435441f737d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotator_1_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annotation_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('annotator_2_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annotation_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('annotator_3_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annotation_3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

        # Add explicit names for foreign keys
        batch_op.create_foreign_key('fk_completed_review_annotator_1', 'user', ['annotator_1_id'], ['id'])
        batch_op.create_foreign_key('fk_completed_review_annotator_2', 'user', ['annotator_2_id'], ['id'])
        batch_op.create_foreign_key('fk_completed_review_annotator_3', 'user', ['annotator_3_id'], ['id'])
        
        batch_op.drop_column('annotations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotations', sa.TEXT(), nullable=False))
        
        # Drop foreign keys with specified names
        batch_op.drop_constraint('fk_completed_review_annotator_1', type_='foreignkey')
        batch_op.drop_constraint('fk_completed_review_annotator_2', type_='foreignkey')
        batch_op.drop_constraint('fk_completed_review_annotator_3', type_='foreignkey')
        
        batch_op.drop_column('completed_at')
        batch_op.drop_column('annotation_3')
        batch_op.drop_column('annotator_3_id')
        batch_op.drop_column('annotation_2')
        batch_op.drop_column('annotator_2_id')
        batch_op.drop_column('annotation_1')
        batch_op.drop_column('annotator_1_id')
    # ### end Alembic commands ###
