"""Fixed 2 annotatorsssssss

Revision ID: e3f1c4492c6a
Revises: f45e356295e2
Create Date: 2025-05-18 03:40:21.085884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f1c4492c6a'
down_revision = 'f45e356295e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.drop_column('model_annotation_done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_annotation_done', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
