"""Fixed 2 annotatorssssss

Revision ID: f45e356295e2
Revises: 53a10ade7b13
Create Date: 2025-05-18 03:36:39.747481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45e356295e2'
down_revision = '53a10ade7b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_annotation_done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.drop_column('model_annotation_done')

    # ### end Alembic commands ###
